### ISSUE TITLE
[3D Map] 点群登録時のリクエストパラメータの説明修正

### ISSUE THREAD

**Issue by Kataoka21** [dprtairc/pntml#50]

**Comment by matono** [comment]
# 点群登録(`POST /pcms/{title}`) にPostする JSON ファイルの説明を再修正

## `transformCRS` の説明

Postされた点群ファイルの座標系．

フォーマットは OPENGIS の EPSG コードを示す URI．
つまり，`https://www.opengis.net/def/crs/EPSG/` を接頭辞に持つ文字列．
例えば以下
* WGS84 → <https://www.opengis.net/def/crs/EPSG/0/4326> 
* 平面直角座標系 9系 → <https://www.opengis.net/def/crs/EPSG/0/6677>

デフォルト値は以下の範囲のいずれかから，`transform` の `origin` の値に基づいて決定する．
* <http://www.opengis.net/def/crs/EPSG/0/32601> から <http://www.opengis.net/def/crs/EPSG/0/32660>
* <http://www.opengis.net/def/crs/EPSG/0/32701> から <http://www.opengis.net/def/crs/EPSG/0/32760>

`transform` が指定されている場合，`transform` の `origin`，`euler`，`scale` に基づいて点群ファイル内の各点の座標を変換したあとの値が，この座標系となることを意味する．

----

Coordinate system of the posted point cloud file.

The format is a URI indicating the EPSG code from opengis.net.
That is, a string prefixed with `https://www.opengis.net/def/crs/EPSG/`.
For example:
* WGS84;  <https://www.opengis.net/def/crs/EPSG/0/4326> 
* JGD2011 / Japan Plane Rectangular CS IX (EPSG:6677); → <https://www.opengis.net/def/crs/EPSG/0/6677>

The default value is determined from one of the following ranges, based on the value of `origin` in `transform`.
* <http://www.opengis.net/def/crs/EPSG/0/32601> to <http://www.opengis.net/def/crs/EPSG/0/32660>
* <http://www.opengis.net/def/crs/EPSG/0/32701> to <http://www.opengis.net/def/crs/EPSG/0/32760>

If `transform` is specified, the coordinate system in `transformCRS` means the coordinates of each point  in the point cloud file which is transformed based on `origin`, `euler` and `scale` in `transform`.


## `transform`の説明

Post された点群ファイルの座標を 変換するための情報．
`transform` の情報に基づいて変換された座標は `transformCRS` で指定した座標系となることを意味する．
`origin` は原点となる WGS84 の座標を表し，オイラー角とスケール値のクォータニオンを使って座標を変換する。

----

PntML uses the information to transform each point in the posted point cloud.

Each point is transformed based on the information of `transform`.
The transformed points are based on the coordinate system specified in `transformCRS`.

The value of 'origin' is the orign point of the posted point cloud based on WGS84.
Each point is transformed using by using quaternion of Euler angles and scale values.


### `origin`の説明

Postされた点群のWGS84に基づく原点．
デフォルト値は[0,0,0]
各値の単位はWGS84の十進角であって，分度秒ではない．

フォーマットは [longitue, latitute]  あるいは [longitue, latitute, altitude] ．
順番が緯度経度ではない点に注意．

点群の座標変換時には WGS84 から `transformCRS` で指定した座標系に変換した上で，各点の座標を変換する．
例えば， 以下のJSONであった場合，WGS84の原点(139.7780996958115, 35.61846131695731, 0)は平面直角座標系9系の(-5003.445813743943, -42328.165818379086, 0) に変換され，これがPostされた点群の原点となる．
```JSON
{
  "transformCRS": "http://www.opengis.net/def/crs/EPSG/0/6677",
  "transform": {
    "origin": [139.7780996958115, 35.61846131695731, 0],
    "euler": [0,0,0],
    "scale": [1,1,1]
  }
}
```

Postされた点群ファイル内のある点 

もし`transformCRS`が指定されなかった場合，`origin` の値によって`transformCRS`を以下から決定する．
* <http://www.opengis.net/def/crs/EPSG/0/32601> から <http://www.opengis.net/def/crs/EPSG/0/32660>
* <http://www.opengis.net/def/crs/EPSG/0/32701> から <http://www.opengis.net/def/crs/EPSG/0/32760>

----

The origin coordinates of the posted point cloud based on WGS84.
The default value is [0,0,0].
The unit of each value is Decimal Degree (DD) of WGS84, but not Degrees Minutes Seconds (DMS).

The format is [longitue, latitute] or [longitue, latitute, altitude].    
Note that the order is not latitude and longitude.

Before transforming the coordinates of each point, the origin point is transformed  from WGS84 to the coordinate system specified by `transformCRS`.
For example, if the following JSON is given, WGS84-based origin (139.7780996958115, 35.61846131695731, 0) is transformed to (-5003.445813743943, -42328.165818379086, 0) in JGD2011 / Japan Plane Rectangular CS IX (EPSG:6677).
This transformed origin coordicates are used as the origin of the posted point cloud.
```JSON
{
  "transformCRS": "http://www.opengis.net/def/crs/EPSG/0/6677",
  "transform": {
    "origin": [139.7780996958115, 35.61846131695731, 0],
    "euler": [0,0,0],
    "scale": [1,1,1]
  }
}
```

If `transformCRS` is not specified, `transformCRS` is determined based on the value of`origin` from the following range of codes.
* <http://www.opengis.net/def/crs/EPSG/0/32601> から <http://www.opengis.net/def/crs/EPSG/0/32660>
* <http://www.opengis.net/def/crs/EPSG/0/32701> から <http://www.opengis.net/def/crs/EPSG/0/32760>


### `euler`の説明

Euler angles to quaternion form, defining the angle around the X-axis (roll) as ψ, the Y-axis (pitch) as θ, and the Z-axis (yaw) as ϕ, by degrees.

The default is [0,0,0]


### `scale`の説明

The scale value of numbers along the X, Y, and Z-axis in order as three scale factors.
The default is [1,1,1]


## `gpsTime`の説明

This timestamp is used for a point cloud which has no explicit GPS timestamp of the data creation/acquisition.

**Comment by matono** [comment]
`POST /pcm/{title}` の説明を一部追加
`config.transform.origin` にデフォルトがなく，もし指定されなければ座標変換が行われないことの説明を追加

      The default is nothing.
      If `origin` is not given, even `euler` and/or `scale` is given, 
      then the coordinate transformation of the posted pointcloud does NOT performed 
      and the pointcloud is stored as it is as the coordinates based on the specified CRS in `transformCRS`.

**Comment by matono** [comment]
`POST /pcm/{title}` と `POST /processes/search`, `POST /processes/voxelize`  に説明を追加

PntMLでは東西方向をX軸，南北方向をY軸と定義している．
そのため（緯度，経度）ではなく（経度，緯度）となる．
また平面直角座標系9系等の座標系も南北方向をX軸，東西方向をY軸としているが，それらとは異なる

    Note that, in PntML, the east-west direction is defined as the x-axis and the north-south direction as the y-axis.
    Therefore, as the order of latlon, (longitude, latitude) is used instead of (latitude, longitude) in PntML.
    Coordinate systems such as Japan Plane Rectangular CS IX also define the north-south direction as the X-axis and the 
    east-west direction as the Y-axis, but the direction of axis is different from these coordinate systems.
